apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: messaging
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:latest
        ports:
          - containerPort: 9092
          - containerPort: 9094
        env:
          - name: KAFKA_NODE_ID
            value: "1"
          - name: CLUSTER_ID
            value: "kafka-cluster"
          - name: KAFKA_PROCESS_ROLES
            value: "controller,broker"
          - name: KAFKA_CONTROLLER_QUORUM_VOTERS
            value: "1@kafka:9093"
          - name: KAFKA_LISTENERS
            value: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093
          - name: KAFKA_ADVERTISED_LISTENERS
            value: PLAINTEXT://kafka.messaging.svc.cluster.local:9092,PLAINTEXT_HOST://kafka:9094
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: PLAINTEXT
          - name: KAFKA_CONTROLLER_LISTENER_NAMES
            value: CONTROLLER
          - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
            value: "true"
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"
          - name: KAFKA_NUM_PARTITIONS
            value: "3"
          - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
            value: "1"
          - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
            value: "1"
        volumeMounts:
          - name: kafka-data
            mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: messaging
spec:
  ports:
    - name: internal
      port: 9092
    - name: external
      port: 9094
  clusterIP: None
  selector:
    app: kafka
