apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    env: local
    area: apps
---
apiVersion: v1
kind: LimitRange
metadata:
  name: defaults
  namespace: apps
spec:
  limits:
    - type: Container
      default:
        cpu: "250m"
        memory: "512Mi"
      defaultRequest:
        cpu: "100m"
        memory: "256Mi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: baseline
  namespace: apps
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 6Gi
    limits.cpu: "8"
    limits.memory: 10Gi
    pods: "100"
