apiVersion: v1
kind: Namespace
metadata:
  name: ingress
  labels:
    env: local
    area: ingress
---
apiVersion: v1
kind: LimitRange
metadata:
  name: defaults
  namespace: ingress
spec:
  limits:
    - type: Container
      default:
        cpu: "250m"
        memory: "256Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: baseline
  namespace: ingress
spec:
  hard:
    requests.cpu: "3"
    requests.memory: 3Gi
    limits.cpu: "6"
    limits.memory: 6Gi
    pods: "40"
