apiVersion: v1
kind: Namespace
metadata:
  name: messaging
  labels:
    env: local
    area: messaging
---
apiVersion: v1
kind: LimitRange
metadata:
  name: defaults
  namespace: messaging
spec:
  limits:
    - type: Container
      default:
        cpu: "500m"
        memory: "1Gi"
      defaultRequest:
        cpu: "250m"
        memory: "512Mi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: baseline
  namespace: messaging
spec:
  hard:
    requests.cpu: "6"
    requests.memory: 8Gi
    limits.cpu: "12"
    limits.memory: 16Gi
    pods: "60"
