apiVersion: v1
kind: Namespace
metadata:
  name: persistence
  labels:
    env: local
    area: persistence
---
apiVersion: v1
kind: LimitRange
metadata:
  name: defaults
  namespace: persistence
spec:
  limits:
    - type: Container
      default:
        cpu: "500m"
        memory: "1Gi"
      defaultRequest:
        cpu: "250m"
        memory: "512Mi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: baseline
  namespace: persistence
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 10Gi
    limits.cpu: "16"
    limits.memory: 20Gi
    persistentvolumeclaims: "40"
    pods: "70"
