apiVersion: v1
kind: Namespace
metadata:
  name: sandbox
  labels:
    env: local
    area: sandbox
    tier: sandbox
---
apiVersion: v1
kind: LimitRange
metadata:
  name: tight-defaults
  namespace: sandbox
spec:
  limits:
    - type: Container
      default:
        cpu: "150m"
        memory: "256Mi"
      defaultRequest:
        cpu: "50m"
        memory: "128Mi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: guardrails
  namespace: sandbox
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "30"
