# ClusterIssuer for self-signed certs
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-root
spec:
  selfSigned: {}
---
# One certificate for all ingresses under localhost
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: localhost-cert
  namespace: default   # can live in default, but is usable cluster-wide
spec:
  secretName: localhost-cert
  issuerRef:
    name: selfsigned-root
    kind: ClusterIssuer
  commonName: localhost
  dnsNames:
    - localhost
